package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/C-Benzz/assignment1.git/graph/model"
)

// CreateTodo is the resolver for the CreateTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - CreateTodo"))
}

// UpdateTodo is the resolver for the UpdateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input *model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: UpdateTodo - UpdateTodo"))
}

// DeleteTodo is the resolver for the DeleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTodo - DeleteTodo"))
}

// GetAllList is the resolver for the GetAllList field.
func (r *queryResolver) GetAllList(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: GetAllList - GetAllList"))
}

// GetTodoByID is the resolver for the GetTodoByID field.
func (r *queryResolver) GetTodoByID(ctx context.Context, id string) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: GetTodoByID - GetTodoByID"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreatePost - CreatePost"))
}
func (r *mutationResolver) UpdatePost(ctx context.Context, postID int, input *model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: UpdatePost - UpdatePost"))
}
