// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
}

type Todo struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
}
